const cars = {
  "title" : "MES VÉHICULES",
  "addNewText" : "Ajouter votre premier véhicule",
  "infos": "INFORMATIONS",
  "immat" : "Immatriculation",
  "gravage" : "Numéro de gravage",
  "brand": "Marque",
  "model": "Modèle",
  "greyCard" : "Carte grise",
  "carInsurrance" : "ASSURANCE DU VÉHICULE",
  "insurranceName" : "Nom de l'assurance",
  "contractNumber" : "Numéro de contrat",
  "begin" : "Date de début",
  "end" : "Date de fin",
  "greenCard" : "Carte Verte",
  "addCar" : "Ajouter le véhicule",
  "addCarAll" : "Ajouter Véhicule",
  "editCar" : "Modifier le véhicule",
  "numberError" : "Vous devez saisir une immatriculation",
  "brandError" : "Vous devez saisir une marque et un modèle",
  "immatExist" : "Cette plaque d'immatriculation est déjà enregistrée",
  "dateError" : "La date de début d'assurance est postérieure à la date du jour. Valider quand même ?",
  "yes" : "Valider",
  "no" : "Retour",
  "congratz" : "Bravo !",
  "addCarCongratz" : "Tu as ajouté un véhicule.",
  "newFactureText" : "Continue de cumuler des points en entrant ta première facture d'entretien.",
  "newFactureButton" : "Ajouter une facture",
  "firstAddText" : "Il est maintenant l'heure d'ajouter ton premier véhicule.",
  "addNewCarText" : "AJOUTER UNE VOITURE",
  "addNewMotoText" : "AJOUTER UNE MOTO",
}

export default cars
