const login = {
  "introText1": "Centralisez toutes les données de votre véhicule sur un cloud sécurisé",
  "introText2": "Recevez des alertes de vos échéances techniques et administratives",
  "introText3": "Cumulez des points et bénéficiez de privilèges chez nos partenaires",
  "createAccount": "CRÉER UN COMPTE",
  "connect" : "SE CONNECTER",
  "emailDesc" : "Renseignez votre email pour vous connecter en toute sécurité",
  "next" : "SUIVANT",
  "email" : "Email",
  "badEmail" : "Ceci n'est pas une adresse mail",
  "checkTitle" : "VÉRIFICATION",
  "checkDesc" : "Saisissez le code de vérification reçu par email",
  "getAgain" : "Renvoyer le code vérification",
  "code" : "Code",
  "badCode" : "Vous devez saisir un code",
  "badCodeApi" : "Le code saisi est incorrect, réessayer",
  "changePasswordText" : "Saisis un mot de passe pour te connecter",
  "changeForgotPasswordText" : "Saisissez un nouveau mot de passe pour vous connecter",
  "changePasswordRule" : "Un mot de passe doit contenir au minimum 8 caractères, au moins une lettre minuscule et une lettre majuscule, un caractère spécial et un chiffre.",
  "confirm" : "CONFIRMER",
  "password" : "Mot de passe",
  "passwordDoesntMatch" : "Les mots de passes doivent être les mêmes",
  "passwordError" : "Le mot de passe ne respecte pas les règles",
  "noPassword" : "Vous devez saisir votre mot de passe",
  "badCredentials" : "Erreur identifiants",
  "forgotPassword" : "Mot de passe oublié",
  "forgotPasswordTitle" : "MOT DE PASSE OUBLIÉ",
  "forgotPasswordDesc" : "Saisissez votre email pour réinitialiser votre mot de passe",
  "passwordConfirm" : "Confirme ton mot de passe",
}

export default login
